### ISSUE TITLE
Is there a way to revert the orientation?

### ISSUE THREAD

**Issue by omarherri** [CodyHouse/cd-column-chart-changelog#1]
Hi in same cases the bar charts may starts from yAxis like what google already do in their chart library: https://developers.google.com/chart/interactive/docs/gallery/barchart

So my question is it possible to have that and how to to do it ?

**Comment by claudia-romano** [comment]
Hi there,
at the moment it is not possible to create a bar chart using our column chart component. But this is a chart variation that we plan on adding. 

We have a board where you can suggest new components (e.g., Bar Chart):
https://codyhouse.nolt.io/

Cheers!

**Comment by omarherri** [comment]
Yes i agree.. thank you for your reply.
